name = "MatrixFreeRandomizedLinearAlgebra"
uuid = "a69accfa-5557-4533-9d8b-afe141969680"
license = "MIT"
version = "0.1.1"
authors = ["Paul Virally <pvirally@gmail.com>"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CUDA = "5.9.5"
Coverage = "1.8.1"
Documenter = "1.16.1"
LinearAlgebra = "1.12.0"
LinearMaps = "3.11.4"
Random = "1.11.0"
SparseArrays = "1.12.0"
julia = "1.12"
